version: 0.2

phases:
  install:
    commands:
      # Install Docker Slim
      - echo Installing Docker Slim...
      - curl -L -o ds.tar.gz https://github.com/slimtoolkit/slim/releases/download/1.40.11/dist_linux.tar.gz
      - tar xvzf ds.tar.gz
      - mv  dist_linux/slim /usr/local/bin/
      - mv  dist_linux/slim-sensor /usr/local/bin/
      - slim --version

  pre_build:
    commands:
      - echo Logging in to Docker Hub...
      - echo "$DOCKERHUB_ACCESS_TOKEN" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin

  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t $DOCKERHUB_USERNAME/$DOCKER_REPO .

  post_build:
    commands:
      - echo Slimming the Docker image...
      - slim build --http-probe=false $DOCKERHUB_USERNAME/$DOCKER_REPO
      - echo Pushing the Docker image...
      - docker push $DOCKERHUB_USERNAME/$DOCKER_REPO
      - echo Docker image pushed to Docker Hub